name: Flutter CI

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # Use Ubuntu as the runner (GitHub-hosted virtual machine)
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java (required for Android builds)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Adjust based on your needs

      # Step 3: Set up Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4' # Use the version your app is built with
          channel: 'stable'

      # Step 4: Get Flutter dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 5: Run tests (optional, if you have tests)
      - name: Run Flutter tests
        run: flutter test

      # Step 6: Build the APK (for Android)
      - name: Build APK
        run: flutter build apk --release

      # Step 7: Upload the APK as an artifact (optional)
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk